try fix

diff --git a/.github/workflows/make-release.yml b/.github/workflows/make-release.yml
--- a/.github/workflows/make-release.yml
+++ b/.github/workflows/make-release.yml
@@ -22,20 +22,26 @@ jobs:
       - name: Merge changes from `master` branch
         run: |
           git reset --hard origin/master
+          git push -f
 
       - name: Create new tag and push it to repo
         id: tag
         run: |
-          tag_name=v$(date +'%Y.%m.%d')
+          base_tag_name=v$(date +'%Y.%m.%d')
+          tag_name=$base_tag_name
 
-          check_tag_name:
-          if [ $(git tag -l "$tag_name") ]; then
-            $tag_name =~ "\A$(date +'%Y\.%m\.%d')-fix\.(\d+)\z"
-            version="${BASH_REMATCH[1]:=0}"
-            tag_name=v$(date +'%Y.%m.%d')-fix.$version
+          function check_tag_name {
+            if [ $(git tag -l "$tag_name") ]; then
+              regexp="^$base_tag_name-fix\.([0-9]+)$"
+              [[ $tag_name =~ $regexp ]] || echo "Can't extract version" || true
+              version="$((${BASH_REMATCH[1]:--1} + 1))"
+              tag_name="$base_tag_name-fix.$version"
 
-            goto check_tag_name
-          fi
+              check_tag_name
+            fi
+          }
+
+          check_tag_name
           
           git tag $tag_name
           git push origin $tag_name
